openapi: 3.1.0
info:
  title: Tawny
  description: A lastfm Api Proxy
  version: 0.1.0
servers:
  - url: 'https'
  - url: 'http'
paths:
  /user/:username/:
    get:
      description: Get User Info
      security:
        - defaultApiKey: []
      parameters:
      - name: username
        in: path
        required: true
        content:
          description: the username
      responses:
        200:
          description: The fetched User Info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userinfo"
        500:
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/internalError"

  /user/:username/tracks/loved:
    get:
      description: "Get loved tracks of specified User"
      security:
        - defaultApiKey: [ ]
      parameters:
        - name: limit
          in: query
          required: false
          content:
            description: The limit
            schema: false
        - name: page
          in: query
          required: false
          content:
            description: The page you want to get
        - name: username
          in: path
          required: true
          content:
            description: the username
      responses:
        200:
          description: the fetched list of loved songs
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/lovedTracks"
        500:
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/internalError"

security:
  - defaultApiKey: []
components:
  securitySchemes:
    defaultApiKey:
      description: The Api Key you obtained from lastfm
      type: apiKey
      name: authentication
      in: header
  schemas:
    userinfo:
      description: the User Info
      properties:
        id:
          type: number
        name:
          type: string
        realname:
          type: string
        url:
          type: string
        imageurl:
          type: string
        country:
          type: string
        age:
          type: number
        gender:
          type: string
        subscriber:
          type: number
        playcount:
          type: number
        playlists:
          type: number
        bootstrap:
          type: number
        registered:
          type: date
    internalError:
      description: internal server error
      properties:
        code:
          type: number
        error:
          type: string
        data:
          properties:
            request:
              properties:
                host:
                  type: string
                path:
                  type: string
                query:
                  type: string
                method:
                  type: string
    tr1:
      properties:
        name:
          type: string
        mbid:
          type: string
        url:
          type: url
        date:
          type: date
        image:
          type: url
    lovedTracks:
      properties:
        track:
          $ref: "#/components/schemas/internalError"
